sudo: required
services:
 - docker

before_install:
 - docker build -t pipeline11/nodetravis -f Dockerfile.dev .
  
scripts:
 - docker run pipeline11/nodetravis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "proddocker"
  env: "Proddocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-262098914696"
  bucket_path: "proddocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
